### PR TITLE
Deduplicate soc2 controls.

### PR DESCRIPTION
**Pull request by rhoboat**

### CODE REVIEW

**Comment by misraved** [comment]
@rhoboat Thanks for using Steampipe 👍  Glad to see that you are working through the SOC2 controls.

We will definitely look into this PR and provide you with the feedback 👍

**Comment by rhoboat** [comment]
@misraved Hi there! I made this PR as a test locally for deduplicating controls across benchmarks. I definitely do not think this is the way to do it, and do not want feedback on this particular PR, so I've converted it to a draft.

Do you think there's any merit in creating a deduper at the `steampipe`-repo level? If so I'll open an issue there to discuss design/pro/cons.

Some initial rough thoughts:

Benefits:
* run each control only once, might be somewhat more performant even though the checks are pretty quick
* show the results for alarms/errors only once for each failure. currently it can look like you have multiple failures when it's the same control run and failing multiple times.
* easier to remediate when going through results because of no duplication

Questions:
* how should the results be grouped? currently they're grouped under benchmark/standard. but if a standard no longer does a check because it was a duplicate, how do we show results?
* should there be a special flag for deduplicating the results, once we figure out how to group/organize them?
ather than in this mod, that can run each control only once, and then group the results by standard? I'll have to think about the UX of this, but something like:

**Comment by rajlearner17** [comment]
@rhoboat appreciate your thoughts around this, I guess this is a broader perspective discussion, which requires other experts from our team to participate. With my basic understanding from your note, just wanted to clarify, so that we can route other persons

I am just giving an example below to be specific, pls correct me if, I am wrong -- this may help others to understand and feedback

When you mean **` deduplicating controls across benchmarks`**, does this mean if we have used e.g. **` control.ec2_instance_in_vpc (EC2 instances should be in a VPC)`** in multiple controls in the same benchmark? to be more specific 

**HIPAA** > 
**Benchmark: 164.308 Administrative Safeguards**  >>  uses `control.ec2_instance_in_vpc` in 
- 164.308(a)(1)(ii)(B) Risk Management
- 164.308(a)(3)(i) Workforce security

** Benchmark: 164.312 Technical Safeguards**  >>
- 164.312(e)(1) Transmission security
- 164.312(a)(1) Access control

if all the above is true, then you are suggesting to have an approach, where we can leverage the **benefits** section mentioned by you?

Yes, we have observed the same while developing the controls for different benchmarks. This is definitely something we can discuss internally/community to gather feedback. 

Initially, when we started developing mods, particularly with AWS, we found AWS implements a similar approach to use the same control across multiple benchmarks or within the benchmark. 
The reason can be, end-user may want to build a full compliance report for a specific benchmark or can be specific sections of the benchmark independently by executing controls.

Similarly, in steampipe we can execute 

`steampipe check aws_compliance.benchmark.hipaa_164_312` or  
`steampipe check aws_compliance.benchmark.hipaa_164_308_a_1_ii_b`  

This may provide flexibility and an established pattern to start with. Additionally, steampipe uses caching for better performance of the query, when re-used, refer to [Better concurrency and caching](https://steampipe.io/blog/release-0-10-0)

But it's fair to think if we can be smart enough to address the deduplicating controls across benchmarks and some of the points you have mentioned. Will tie up a few others to provide their feedback and take it forward. Happy to see your further response on it as well.

**Comment by cbruno10** [comment]
Hey @rhoboat , thanks for the PR and start of the discussion!

As @rajlearner17 had mentioned, Steampipe does leverage caching (unless explicitly disabled), so even if multiple controls/queries are run multiple times in a single `steampipe check` run, the results are cached, so performance wise re-running controls shouldn't majorly impact performance.

For the SOC2 benchmark, and others, we chose to re-use controls across multiple benchmarks and controls when the source material (in this case, AWS) has them mapped this way to provide a complete set of controls. For instance, if we remove `benchmark.soc_2_cc_3_4`, and a user runs the full SOC2 report, they may notice that CC3.4 is missing and think that the benchmark is incomplete.

When you run the SOC2 benchmark and any others, how do you use the results from Steampipe? Are you verifying that each section is present and passing? Or do you just check that the full report (no matter what sections there are) are all passing? And in regards to duplicates, do they diminish the value of the report for you in any way based on how you use or export the results?

**Comment by rhoboat** [comment]
Thanks for engaging on this discussion!

With the added knowledge that steampipe leverages caching unless disabled, I think the benefits of deduplicating controls across benchmarks is significantly reduced. It would come down to only:

> * show the results for alarms/errors only once for each failure. currently it can look like you have multiple failures when it's the same control run and failing multiple times.

And based on that, I don't think it's worth doing this work.

To elaborate on why: We use the results in order to put remediation in place to address the failing steampipe checks. So, typically we write the results out to html for easier reading in a browser, then make a spreadsheet/list of issues based on the failures; then we create GitHub issues for each of those. So the particular benchmark number that we're targetting is no longer really a concern once we start the remediation. It's still essential / useful as a report for us, to make sure all the checks are run in the overall report, and all the benchmark standards are covered.

Seeing the duplicate errors does not diminish the value of the report--which is a good point.

**Comment by cbruno10** [comment]
Thanks for the explanation of your use case @rhoboat , it's always helpful for us to understand how people are using our plugins and mods.

Also, as a possible alternative, if there are specific queries that are only used in a subset of the SOC2 controls, or are outside of the scope of SOC2, you can add new benchmarks and controls either in this mod (in a fork), or in another mod, that leverages the queries in this mod. 

I'll be closing this PR based on your comments above, but please let us know if you have any other questions!

**Pull request closed without merging**
