### PR TITLE
Optional quotes in Metric Filter for AWS Organization

### PR DESCRIPTION
**Pull request by marinalimeira**
Issue: #553

### CODE REVIEW

**Review by misraved — APPROVED** [review]

**Comment by misraved** [comment]
Welcome to Steampipe @marinalimeira and thanks for raising this PR.

On similar lines do we also need to update `log_metric_filter_unauthorized_api` query?

```
    and filter.filter_pattern ~ '\$\.errorCode\s*=\s*"\*UnauthorizedOperation".+\$\.errorCode\s*=\s*"AccessDenied\*".+\$\.sourceIPAddress\s*!=\s*"delivery.logs.amazonaws.com".+\$\.eventName\s*!=\s*"HeadBucket"'
```

**Comment by marinalimeira** [comment]
> Welcome to Steampipe @marinalimeira and thanks for raising this PR.
> 
> On similar lines do we also need to update `log_metric_filter_unauthorized_api` query?
> 
> ```
>     and filter.filter_pattern ~ '\$\.errorCode\s*=\s*"\*UnauthorizedOperation".+\$\.errorCode\s*=\s*"AccessDenied\*".+\$\.sourceIPAddress\s*!=\s*"delivery.logs.amazonaws.com".+\$\.eventName\s*!=\s*"HeadBucket"'
> ```

I don't know what is the difference, but this query works for me:
```
> select filter_pattern from aws_cloudwatch_log_metric_filter where filter_pattern ~ '\$\.errorCode\s*=\s*"\*UnauthorizedOperation".+\$\.errorCode\s*=\s*"AccessDenied\*".+\$\.sourceIPAddress\s*!=\s*"delivery.logs.amazonaws.com".+\$\.eventName\s*!=\s*"HeadBucket"'
+--------------------------------------------------------------------------------------------------------------------------------------------------------------->
| filter_pattern                                                                                                                                                >
+--------------------------------------------------------------------------------------------------------------------------------------------------------------->
| { (($.errorCode = "*UnauthorizedOperation") || ($.errorCode = "AccessDenied*")) && (($.sourceIPAddress != "delivery.logs.amazonaws.com") && ($.eventName != "H>
+--------------------------------------------------------------------------------------------------------------------------------------------------------------->

```

**Comment by marinalimeira** [comment]
> Welcome to Steampipe @marinalimeira and thanks for raising this PR.

Thanks!

> 
> On similar lines do we also need to update `log_metric_filter_unauthorized_api` query?
> 
> ```
>     and filter.filter_pattern ~ '\$\.errorCode\s*=\s*"\*UnauthorizedOperation".+\$\.errorCode\s*=\s*"AccessDenied\*".+\$\.sourceIPAddress\s*!=\s*"delivery.logs.amazonaws.com".+\$\.eventName\s*!=\s*"HeadBucket"'
> ```

I don't know what is the difference, but this query works for me:
```
> select filter_pattern from aws_cloudwatch_log_metric_filter where filter_pattern ~ '\$\.errorCode\s*=\s*"\*UnauthorizedOperation".+\$\.errorCode\s*=\s*"AccessDenied\*".+\$\.sourceIPAddress\s*!=\s*"delivery.logs.amazonaws.com".+\$\.eventName\s*!=\s*"HeadBucket"'
+--------------------------------------------------------------------------------------------------------------------------------------------------------------->
| filter_pattern                                                                                                                                                >
+--------------------------------------------------------------------------------------------------------------------------------------------------------------->
| { (($.errorCode = "*UnauthorizedOperation") || ($.errorCode = "AccessDenied*")) && (($.sourceIPAddress != "delivery.logs.amazonaws.com") && ($.eventName != "H>
+--------------------------------------------------------------------------------------------------------------------------------------------------------------->

```

**Comment by marinalimeira** [comment]
I am comparing this with the CIS AWS Benchmark pdf, there are some recommendations with quotes in the filter patterns and some don't. 

The lack of pattern in CIS's own document across the value for `eventName`, makes it unpredictable on standardize all queries with our without quotes. e.g. the recommendation 4.4 doesn't wrap it in quotes, but the 4.15 (the one in question in this PR), does.

I don't know what's the best approach here, I will leave this to you on releasing this PR or not.

On my side, if this PR doesn't go through, I can re-deploy the filter without the quotes, in order to make the check pass.

**Comment by misraved** [comment]
Thank you for such a detailed insight @marinalimeira 👍.

The CIS documentation is indeed pretty confusing, however, the changes that you have made in this PR look good to me.

I will do some more testing around the metric filter queries 👍 and push your PR for the release early next week 😄.

Once again, many thanks for bringing this issue to light.

**Comment by marinalimeira** [comment]
Great, thank you for reviewing it so fast!

**Comment by marinalimeira** [comment]
@misraved I made another change. Given this is a regex, we can make the quotes optional. The PR now is not backwards-compatible, and this can be reproduced in the other `filter_pattern` later.

**Comment by rajlearner17** [comment]
@marinalimeira, Thanks for the detailed discussion above.

I agree with your point above; when we developed this CIS section-4, we went through this confusion of having quotes somewhere vs not in some places. I need to learn how they test these use cases 😄.

Anyway, in my experiment, I see no difference with a quote, i.e. match a single term vs with `?`, i.e. match single and multiple terms ([ref](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html#matching-terms-events)). My resources with current patterns may not meet all required matches. We need some testing time to check this and get back on this issue to ensure we follow similar patterns across control 4.8 till 4.15. 

Meanwhile glad that, you are unblocked with the change. Please do share more feedback, if any.

**Pull request closed without merging**
